# Generated by Django 3.2.5 on 2021-07-18 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CellUniqueUsersKPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interval_start_timestamp', models.DateTimeField()),
                ('interval_end_timestamp', models.DateTimeField()),
                ('interval', models.SmallIntegerField(choices=[(1, 'Five Minutes'), (2, 'One Hour')], default=1)),
                ('cell_id', models.IntegerField()),
                ('number_of_unique_users', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_file_count', models.IntegerField()),
                ('end_date', models.DateTimeField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceTrafficVolKPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interval_start_timestamp', models.DateTimeField()),
                ('interval_end_timestamp', models.DateTimeField()),
                ('interval', models.SmallIntegerField(choices=[(1, 'Five Minutes'), (2, 'One Hour')], default=1)),
                ('service_id', models.IntegerField()),
                ('total_bytes', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
